# Generated by Django 5.2 on 2025-04-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_helathcare_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='temp_dummy',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
