# Generated by Django 5.2 on 2025-04-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.URLField()),
                ('category', models.CharField(choices=[('skin', 'Skin Care'), ('cold', 'Cold & Cough'), ('diabetes', 'Diabetes')], default='skin', max_length=20)),
            ],
        ),
    ]
