# Generated by Django 5.2 on 2025-04-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwiftCart', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('yet', 'Yet to be Delivered'), ('delivered', 'Delivered')], default='ordered', max_length=20),
        ),
    ]
