# Generated by Django 5.2 on 2025-05-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwiftCart', '0003_order_is_paid_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(default='skin', max_length=20),
        ),
    ]
